apiVersion: v1
kind: Service
metadata:
  name: {{ include "faktory.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "faktory.name" . }}
    helm.sh/chart: {{ include "faktory.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.commands_port }}
      targetPort: commands
      protocol: TCP
      name: commands
    - port: {{ .Values.service.ui_port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app.kubernetes.io/name: {{ include "faktory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
